/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type AppointmentStatus = "cancelled" | "completed" | "confirmed" | "pending";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Numeric = ColumnType<string, number | string, number | string>;

export type PaymentMethod = "moncash" | "natcash";

export type PropertyCategory = "apartment" | "commercial" | "house_rent" | "house_sale" | "land_sale";

export type ReportReason = "fake_listing" | "inappropriate" | "other" | "scam" | "wrong_info";

export type ReportStatus = "action_taken" | "dismissed" | "pending" | "reviewed";

export type SubscriptionStatus = "active" | "cancelled" | "expired" | "pending";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type UserRole = "admin" | "agent" | "user";

export type VerificationStatus = "pending" | "rejected" | "verified";

export interface AgentDocuments {
  createdAt: Generated<Timestamp | null>;
  documentData: string;
  documentType: string;
  id: Generated<number>;
  userId: number;
}

export interface Appointments {
  agentId: number;
  clientEmail: string | null;
  clientName: string;
  clientPhone: string;
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  message: string | null;
  preferredDate: Timestamp;
  preferredTime: string;
  propertyId: number;
  status: Generated<AppointmentStatus>;
  updatedAt: Generated<Timestamp | null>;
}

export interface Favorites {
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  propertyId: number;
  userId: number;
}

export interface LoginAttempts {
  attemptedAt: Generated<Timestamp | null>;
  email: string;
  id: Generated<number>;
  success: Generated<boolean | null>;
}

export interface PasswordResetTokens {
  createdAt: Generated<Timestamp | null>;
  expiresAt: Timestamp;
  id: Generated<number>;
  token: string;
  usedAt: Timestamp | null;
  userId: number;
}

export interface Properties {
  address: string | null;
  agentId: number | null;
  areaSqft: number | null;
  bathrooms: number | null;
  bedrooms: number | null;
  category: PropertyCategory;
  city: string;
  createdAt: Generated<Timestamp | null>;
  description: string | null;
  id: Generated<number>;
  isFeatured: Generated<boolean | null>;
  phone: string | null;
  price: Numeric;
  title: string;
  updatedAt: Generated<Timestamp | null>;
  whatsapp: string | null;
}

export interface PropertyImages {
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  imageUrl: string;
  isPrimary: Generated<boolean | null>;
  propertyId: number;
}

export interface PropertyReports {
  adminNotes: string | null;
  createdAt: Generated<Timestamp | null>;
  description: string;
  id: Generated<number>;
  propertyId: number;
  reason: ReportReason;
  reporterEmail: string | null;
  reporterId: number | null;
  status: Generated<ReportStatus>;
  updatedAt: Generated<Timestamp | null>;
}

export interface Reviews {
  agentId: number;
  comment: string | null;
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  propertyId: number | null;
  rating: number;
  reviewerId: number;
  updatedAt: Generated<Timestamp | null>;
}

export interface Sessions {
  createdAt: Generated<Timestamp | null>;
  expiresAt: Timestamp;
  id: string;
  lastAccessed: Generated<Timestamp | null>;
  userId: number;
}

export interface SmsResetCodes {
  code: string;
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: Generated<number>;
  phone: string;
  usedAt: Timestamp | null;
  userId: number;
}

export interface SubscriptionPlans {
  canFeatureListings: Generated<boolean>;
  createdAt: Generated<Timestamp | null>;
  description: string | null;
  hasPrioritySupport: Generated<boolean>;
  hasProBadge: Generated<boolean>;
  hasVipBadge: Generated<boolean>;
  id: Generated<number>;
  isActive: Generated<boolean>;
  maxFeatured: Generated<number>;
  maxListings: Generated<number>;
  maxPhotosPerListing: Generated<number>;
  name: string;
  priceHtg: Generated<Numeric>;
  slug: string;
  sortOrder: Generated<number>;
}

export interface UserPasswords {
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  passwordHash: string;
  userId: number;
}

export interface Users {
  avatarUrl: string | null;
  bio: string | null;
  createdAt: Generated<Timestamp | null>;
  displayName: string;
  email: string;
  id: Generated<number>;
  phone: string | null;
  role: Generated<UserRole>;
  slug: string | null;
  updatedAt: Generated<Timestamp | null>;
  verificationStatus: Generated<VerificationStatus | null>;
  whatsapp: string | null;
}

export interface UserSubscriptions {
  cancelledAt: Timestamp | null;
  createdAt: Generated<Timestamp | null>;
  expiresAt: Timestamp | null;
  id: Generated<number>;
  paymentMethod: PaymentMethod | null;
  paymentReference: string | null;
  planId: number;
  startedAt: Timestamp | null;
  status: Generated<SubscriptionStatus>;
  userId: number;
}

export interface WhatsappContacts {
  agentId: number;
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  propertyId: number;
  userId: number | null;
  visitorIdentifier: string | null;
}

export interface DB {
  agentDocuments: AgentDocuments;
  appointments: Appointments;
  favorites: Favorites;
  loginAttempts: LoginAttempts;
  passwordResetTokens: PasswordResetTokens;
  properties: Properties;
  propertyImages: PropertyImages;
  propertyReports: PropertyReports;
  reviews: Reviews;
  sessions: Sessions;
  smsResetCodes: SmsResetCodes;
  subscriptionPlans: SubscriptionPlans;
  userPasswords: UserPasswords;
  users: Users;
  userSubscriptions: UserSubscriptions;
  whatsappContacts: WhatsappContacts;
}


// Use these for zod schema enums or other purposes, since the kysely enums are just types
export const UserRoleArrayValues: [UserRole, ...UserRole[]] = ["admin","agent","user"];
export const PropertyCategoryArrayValues: [PropertyCategory, ...PropertyCategory[]] = ["apartment","commercial","house_rent","house_sale","land_sale"];
export const VerificationStatusArrayValues: [VerificationStatus, ...VerificationStatus[]] = ["pending","rejected","verified"];
export const SubscriptionStatusArrayValues: [SubscriptionStatus, ...SubscriptionStatus[]] = ["active","cancelled","expired","pending"];
export const PaymentMethodArrayValues: [PaymentMethod, ...PaymentMethod[]] = ["moncash","natcash"];
export const AppointmentStatusArrayValues: [AppointmentStatus, ...AppointmentStatus[]] = ["cancelled","completed","confirmed","pending"];
export const ReportReasonArrayValues: [ReportReason, ...ReportReason[]] = ["fake_listing","inappropriate","other","scam","wrong_info"];
export const ReportStatusArrayValues: [ReportStatus, ...ReportStatus[]] = ["action_taken","dismissed","pending","reviewed"];
// Note: kysely maps the table/column/enum names from snake_case to camelCase and PascalCase. When running SQL statements, make sure to use snake_case, but TypeScript code should use camelCase or PascalCase.